# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce00a291ead432ca9084afd818ffe6d43f636f1d53ba5e964887748859ea2c91880504c0ccae254a7dee4588c53f2645ed8bdf6f74ca18455d96771a7d597141

test:
  secret_key_base: 12ba1a4e3e4feddfaf73b0913076838ace0e79550bacc6bc602b963f2ac3081ff49192e0aee8ec3bc486144ed4e86ec293d1f6c104f19d121ccd3d20bb717818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
